### ISSUE TITLE
Document new WP 5.7 features 

### ISSUE THREAD

**Issue by PriyaBhatia0210** [humanmade/altis-documentation#201]
Add documentation for new WP 5.7 features:
- [x] Robots API to be documented in the SEO Module altis-seo#47
- [x] Lazy loading iFrames

**Comment by roborourke** [comment]
Not sure we really need the docs on iframe lazy loading? What do you think Chris? Given that it's a passive thing that WP just does.

**Comment by jazzsequence** [comment]
Well, we have a page about lazy loading in the media docs (which is handled by gaussholder but technically was added to core, too, in a different format), so I figured that since we have a place for it, we can drop some notes about the lazy loading for iframes, too. There's some small amount of development consideration that's part of it.
